[versions]
agp = "9.0.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity-activity-compose = "1.11.0"
androidx-appcompat-appcompat = "1.7.1"
androidx-core-core-ktx = "1.17.0"
androidx-test-espresso-espresso-core = "3.7.0"
androidx-lifecycle = "2.10.0-alpha08"
androidx-test-ext-junit = "1.3.0"
composeMultiplatform = "1.11.0-alpha02"
datastore = "1.2.0"
junit-junit = "4.13.2"
jdk = "25"
koin = "4.2.0-RC1"
io-insert-koin-koin-annotations = "4.2.0-RC1"
io-insert-koin-koin-compiler-gradle-plugin = "0.3.0"
koin-compose = "4.2.0-RC1"
kotest = "6.1.1"
kotlin = "2.3.20-Beta2"
de-jensklingenberg-ktorfit-ktorfit-lib-light = "2.7.2"
kotlinx-coroutines = "1.10.2"
com-google-devtools-ksp-com-google-devtools-ksp-gradle-plugin = "2.3.5"
ktor = "3.4.0"
ch-qos-logback-logback-classic = "1.5.24"
material = "1.13.0"
org-jetbrains-compose-material3-material3 = "1.10.0-alpha05"
org-jetbrains-compose-material-material-icons-extended = "1.7.3"
io-github-khubaibkhan4-mediaplayer-kmp = "2.1.0"
org-jetbrains-androidx-navigation3-navigation3-ui = "1.1.0-alpha02"
androidx-navigation-navigation-compose = "2.9.7"
room = "2.8.4"
sqlite = "2.6.2"
koin-compiler-gradle-plugin = "0.3.0"
jimmer = "0.9.120"
enaium-jimmer-gradle = "0.0.34"
sqlite-jdbc = "3.49.1.0"
openapi-generator = "7.12.0"
jimmer-ksp-version = "0.9.120"
akka-stream-netty-all-2-13-version = "0.1.18"
ktor-banner-version = "2026.02.10"
filekit-core-version = "0.12.0"
gadulka-version = "1.9.0"
ioc-processor-version = "2026.02.17"
ioc-core = "2026.02.16"
tool-json-version = "2026.02.04"
network-starter-version = "0.0.672"
[libraries]
#---------------------- com.android.tools.build -----------------------
com-android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
com-android-tools-build-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
#--------------------------- io.insert-koin ---------------------------
io-insert-koin-koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "io-insert-koin-koin-annotations" }
io-insert-koin-koin-compiler-gradle-plugin = { module = "io.insert-koin:koin-compiler-gradle-plugin", version.ref = "io-insert-koin-koin-compiler-gradle-plugin" }
io-insert-koin-koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
io-insert-koin-koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
de-jensklingenberg-ktorfit-ktorfit-lib-light = { module = "de.jensklingenberg.ktorfit:ktorfit-lib-light", version.ref = "de-jensklingenberg-ktorfit-ktorfit-lib-light" }
#----------------------------- io.kotest ------------------------------
io-kotest-kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
io-kotest-kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
#------------------------------ io.ktor -------------------------------
io-ktor-ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
io-ktor-ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
io-ktor-ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
io-ktor-ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
io-ktor-ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
io-ktor-ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
io-ktor-ktor-server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor" }
io-ktor-ktor-server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }
io-ktor-ktor-server-routing-openapi = { module = "io.ktor:ktor-server-routing-openapi", version.ref = "ktor" }
io-ktor-ktor-server-core-jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
io-ktor-ktor-server-netty-jvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
io-ktor-ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
io-ktor-ktor-server-test-host-jvm = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
#------------------ org.jetbrains.androidx.lifecycle ------------------
org-jetbrains-androidx-lifecycle-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
org-jetbrains-androidx-lifecycle-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
org-jetbrains-androidx-lifecycle-lifecycle-viewmodel-navigation3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
#---------------------- org.jetbrains.compose.ui ----------------------
org-jetbrains-compose-ui-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
org-jetbrains-compose-ui-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
org-jetbrains-compose-ui-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
#------------------------ org.jetbrains.kotlin ------------------------
org-jetbrains-kotlin-compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
#----------------------- org.jetbrains.kotlinx ------------------------
org-jetbrains-kotlinx-kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
#---------------------------- single group ----------------------------
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-activity-compose" }
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat-appcompat" }
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-core-ktx" }
androidx-test-espresso-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso-espresso-core" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-navigation-compose" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
org-jetbrains-compose-components-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
org-jetbrains-compose-foundation-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
org-jetbrains-compose-compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }
org-jetbrains-compose-material3-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "org-jetbrains-compose-material3-material3" }
org-jetbrains-compose-runtime-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
junit-junit = { module = "junit:junit", version.ref = "junit-junit" }
io-github-khubaibkhan4-mediaplayer-kmp = { module = "io.github.khubaibkhan4:mediaplayer-kmp", version.ref = "io-github-khubaibkhan4-mediaplayer-kmp" }
com-google-devtools-ksp-com-google-devtools-ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "com-google-devtools-ksp-com-google-devtools-ksp-gradle-plugin" }
ch-qos-logback-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "ch-qos-logback-logback-classic" }
org-jetbrains-compose-material-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "org-jetbrains-compose-material-material-icons-extended" }
org-jetbrains-androidx-navigation3-navigation3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "org-jetbrains-androidx-navigation3-navigation3-ui" }
koin-compiler-gradle-plugin = { group = "io.insert-koin", name = "koin-compiler-gradle-plugin", version.ref = "koin-compiler-gradle-plugin" }
jimmer-sql-kotlin = { module = "org.babyfish.jimmer:jimmer-sql-kotlin", version.ref = "jimmer" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
jimmer-ksp = { group = "org.babyfish.jimmer", name = "jimmer-ksp", version.ref = "jimmer" }
ktor-banner = { group = "site.addzero", name = "ktor-banner", version.ref = "ktor-banner-version" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
filekit-core = { group = "io.github.vinceglb", name = "filekit-core", version.ref = "filekit-core-version" }
filekit-dialogs = { group = "io.github.vinceglb", name = "filekit-dialogs", version.ref = "filekit-core-version" }
filekit-dialogs-compose = { group = "io.github.vinceglb", name = "filekit-dialogs-compose", version.ref = "filekit-core-version" }
filekit-coil = { group = "io.github.vinceglb", name = "filekit-coil", version.ref = "filekit-core-version" }
gadulka = { group = "eu.iamkonstantin.gadulka", name = "gadulka", version.ref = "gadulka-version" }
ioc-processor = { group = "site.addzero", name = "ioc-processor", version.ref = "ioc-processor-version" }
ioc-core = { group = "site.addzero", name = "ioc-core", version.ref = "ioc-core" }
kotlin-gadulka = { group = "eu.iamkonstantin.kotlin", name = "gadulka", version.ref = "gadulka-version" }
tool-json = { group = "site.addzero", name = "tool-json", version.ref = "tool-json-version" }
network-starter = { group = "site.addzero", name = "network-starter", version.ref = "network-starter-version" }
[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "io-insert-koin-koin-compiler-gradle-plugin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
com-google-devtools-ksp-com-google-devtools-ksp-gradle-plugin = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp-com-google-devtools-ksp-gradle-plugin" }
de-jensklingenberg-ktorfit-ktorfit-lib-light = { id = "de.jensklingenberg.ktorfit", version.ref = "de-jensklingenberg-ktorfit-ktorfit-lib-light" }
enaium-jimmer-gradle = { id = "cn.enaium.jimmer.gradle", version.ref = "enaium-jimmer-gradle" }
ktor-plugin = { id = "io.ktor.plugin", version.ref = "ktor" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
